openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'SIMPLESHOP'
  description: 'this is a simple api.'
  termsOfService: www.sample.com/terms-of-use
  contact:
    name: xkfx
    url: https://www.cnblogs.com/xkxf/
    email: wyzxkfx@gmail.com
  license:
    name: DIY License
    url: https://www.sample.com/license

servers:
  - url: http://localhost:8080/test/api/v1
    description: Dev server

  - url: http://localhost:8080/test/api/v2
    description: Dev server

  - url: https://www.sample.com/test/api/v
    description: Prod server

paths:

  /users:
    post:
      description: Creates a new user in data base
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/user-register'
      responses:
        200:
          description: Successful created a new user
        400:
          description: Registration failed

    get:
      description: Obtain infomation about user from the database
      parameters:
        - in: query
          name: username
          required: true
          description: The username of the user
          schema:
            type: string
            example: xkfx1997
        - in: query
          name: password
          required: true
          description: The password of the user
          schema:
            type: string
            example: 123

      responses:
        200:
          description: Successful pull of user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Pull of user info failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /items:
    delete:
      description: delete item by id
      parameters:
        - in: query
          name: id
          required: true
          description: The id of the item
          schema:
            type: string
            example: 21400
      responses:
        204:
          description: Successful
        400:
          description: failed

components:
  schemas:
    users:
      description: Array of simpleUser info
      type: array
      items:
        $ref: '#/components/schemas/user'

    user:
      description: Model containing simpleUser info
      properties:
        id:
          type: integer
          example: 10001

        username:
          type: string
          example: admin

        type:
          type: integer
          example: 1

    user-register:
      description: Model containing simpleUser-register info
      properties:
        username:
          type: string
          example: admin

        password:
          type: string
          example: abc12345

        type:
          type: integer
          example: 1